### ISSUE TITLE
Exception Explanation

### ISSUE THREAD

**Issue by keithjbell** [NewSpring/Excavator#121] opened 2015-04-09 19:52 UTC
What is this exception telling me. I'm having trouble trying to get it fixed. 
![screen shot 2015-04-09 at 2 51 20 pm](https://cloud.githubusercontent.com/assets/9340628/7075483/093f8694-dec8-11e4-921b-798995f15281.png)

**Comment by dcs619** [comment] 2015-04-14 14:19
It sounds like there's a column missing or potentially a column without a header.  If you've upgraded to Rock 3.1 Excavator doesn't support that yet.

**Comment by bacsrlette** [comment] 2015-04-22 17:15
@dcs619 dcs619 - what versions of the Rock does Excavator support?

**Comment by dcs619** [comment] 2015-05-11 19:54
@keithjbell I just released an update to support Rock 3.2.  If you still have trouble can you send me a blank copy of the Family.csv you're using?  I don't need any data, just the headers.

**Comment by dcs619** [comment] 2015-11-10 20:16
Not able to reproduce, closing.

**Closed by dcs619** 2015-11-10 20:16 UTC
Labels: needsreproduction
