### ISSUE TITLE
Is Excavator compatibility with RockRMS 3.1?

### ISSUE THREAD

**Issue by bacsrlette** [NewSpring/Excavator#124] opened 2015-04-22 17:13 UTC
Please confirm the versions of RockRMS that Excavator is compatible with. 

Is it compatible with version 3.1? We are having issues importing F1 data.

**Comment by dcs619** [comment] 2015-04-22 17:49
I'm still testing all of the changes with 3.1 so only official support is 2.1.  Duplicate of #122.

**Closed by dcs619** 2015-04-22 17:49 UTC
