### ISSUE TITLE
CSV: Import Fails With Any Modifications to CSV

### ISSUE THREAD

**Issue by BelAirIT** [NewSpring/Excavator#106] opened 2015-01-05 21:23 UTC
The only way I've been able to get the utility to display "Successfully read the import file" is when downloading the sample.  This is strange because the Wiki makes it sound like there are some tight requirements for this to work and the sample file has all kinds of strange XML and looks nothing like what I'd expect.  If I open the "accepted" file and make even the most minor changes it will be rejected.  Even opening the file and then saving the exact same content fails.

**Comment by dcs619** [comment] 2015-01-05 21:48
Ok, I'll take a look.

**Comment by dcs619** [comment] 2015-01-05 21:49
What program are you using to open the sample file? @BelAirIT

**Comment by BelAirIT** [comment] 2015-01-05 22:06
Microsoft Office 2013 (PC Windows 7 x64)

**Comment by dcs619** [comment] 2015-01-06 03:14
I'm not able to reproduce this, but I don't have Office 2013.  I tested using Excel on a mac and LibreOffice on Windows.  

![screenshot 2015-01-05 22 10 45](https://cloud.githubusercontent.com/assets/1210933/5623800/d676fe3e-9527-11e4-8f0a-2ab9996cfbc9.png)
![screenshot 2015-01-05 22 09 49](https://cloud.githubusercontent.com/assets/1210933/5623801/d81ed20c-9527-11e4-84c4-7dccf7b829df.png)

CSV is a pretty well-standardized format, so I can't imagine Excel 2013 not being able to handle the file.  Maybe the links weren't correct? Right click these and Save As: https://raw.githubusercontent.com/NewSpring/Excavator/master/Excavator.CSV/Individual.csv
https://raw.githubusercontent.com/NewSpring/Excavator/master/Excavator.CSV/Family.csv

**Comment by BelAirIT** [comment] 2015-01-06 18:54
The new links work much better.  When right click/downloading the Wiki page link in Chrome it outputs a file looking like this: 
![untitled](https://cloud.githubusercontent.com/assets/7409839/5634127/44485844-9592-11e4-89f6-a51bcb3aff3a.png)

**Comment by dcs619** [comment] 2015-01-06 18:57
Yep, it looks like you downloaded the Github view for the CSV file instead of the file itself.

@ElimAdmin Could you update the CSV file links in the wiki so they point to the raw.github version?  E.g.,
https://github.com/NewSpring/Excavator/blob/master/Excavator.CSV/Family.csv vs https://raw.githubusercontent.com/NewSpring/Excavator/master/Excavator.CSV/Family.csv

**Comment by BelAirIT** [comment] 2015-01-06 19:28
It's almost working now.  Just getting a: CheckExistingImport,"The named import user was note found, and none could be created." error when using Admin as the user doing the import.

**Comment by dcs619** [comment] 2015-01-06 19:35
You should only get that error if you renamed/changed the default Admin
account in Rock.   Can you double check that Admin is the right name on
that user?

**Comment by BelAirIT** [comment] 2015-01-06 20:13
The account's name is Admin Admin with a database login account of Administrator.  I tried Administrator but that gave me the same error.

**Comment by dcs619** [comment] 2015-01-07 15:05
I'm not sure what the problem is.  This is the code that runs the lookup: https://github.com/NewSpring/Excavator/blob/master/Excavator.CSV/CSVComponent.cs#L239

If it can't find a match on the import name, then it just picks the first person in the database.  Somehow your database isn't returning anyone.

**Comment by BelAirIT** [comment] 2015-01-07 17:12
Another strange issue is that no matter what I type into the "Connect to Rock server" fields it always says it completed successfully.

**Comment by BelAirIT** [comment] 2015-01-07 18:07
Figured out what the problem was.  Our developer server has three databases (Rock, RockRMS, RockChMS) and it was defaulting to RockRMS.  The real database is Rock so after manually specifying that it worked!

**Comment by BelAirIT** [comment] 2015-01-07 20:55
Also, I've figured out why editing the file breaks upload capabilities every time.  The file MUST be named Individual.csv so calling it testindividual.csv or individual2.csv will always fail.

**Comment by ElimAdmin** [comment] 2015-01-07 22:27
I have updated the Excavator.csv wiki to make this clear.

**Comment by dcs619** [comment] 2015-01-08 14:19
@BelAirIT @ElimAdmin We can change that behavior.  I'll file an issue so that as long as Individual or Family is in the name it will discover it correctly.  That would also allow you to batch each import with 1k (or more) if you wanted to.

Closing issue.

**Closed by dcs619** 2015-01-08 14:19 UTC
Labels: needsreproduction
